### ISSUE TITLE
Internet traffic issue

### ISSUE THREAD

**Issue by p-hells** [smooch/smooch-android#107]
Hello!
We use "Smooch support" service in our application. Implementation is :

gradle:
`dependencies {`
`...`
`implementation 'io.smooch:core:4.2.0'`
`implementation 'io.smooch:ui:4.2.0'`
`}`

App:

`@Override`
`public void onCreate() {`
`    super.onCreate();`
`    Smooch.init(this, BuildConfig.SMOOCH_ID);`
`}`

Calling method:

`public static void openSupportChat(final Activity context) {`
`	...`
`	User.getCurrentUser().setFirstName(name);`
`	User.getCurrentUser().setLastName("");`
`	try {`
`       ConversationActivity.show(context);`
`    } catch (Throwable e) {`
`    }`
`}`

Everything works fine. But. Several days ago our customer reported a strange issue. He noticed the HUGE internet traffic that go through Smooch IPs which are started with 13.33.244... (media.smooch.io). 
See screenshots below, it downloaded  about 8 GB in a couple of days.
We are very worried abouth this situation. Please provide us with the answer as soon as possible. If you need any additional information let us know.

![help1](https://user-images.githubusercontent.com/7901912/34721427-b9fc1e80-f553-11e7-8076-94d3e483429a.png)
![help2](https://user-images.githubusercontent.com/7901912/34721435-be3d775a-f553-11e7-8a8e-c4c82274454f.png)

**Comment by wmora** [comment]
That's strange, images are downloaded and cached on demand when ConversationActivity is open. With that said, version 4.2.0 is almost a year old and we've released many optimizations since then, one of them specific to the way we display messages and cache images. I suggest you upgrade to the latest version and let us know if the issue persists

**Comment by p-hells** [comment]
Ok, we'll try it and let you know about results

**Comment by p-hells** [comment]
Updating to 5.7.3 didn't resolve the issue. Our customer provided the short video demonstarting it. Please check it. Asus ZenFone 6, Android 5.0.
We hope to hear you soon.

[20180111_205642.zip](https://github.com/smooch/smooch-android/files/1625108/20180111_205642.zip)

**Comment by wmora** [comment]
Thanks for reaching out and sorry for the delay. If you are a paid user, please log into the web app and contact our support team there. To keep our service cost effective we unfortunately can’t offer support to all of our free users. Please email help@smooch.io and we will use best effort to respond with some useful tips that may be of help to you.
