### ISSUE TITLE
Couldn't find com.google.gson.annotations.SerializedName.value 

### ISSUE THREAD

**Issue by islamassi** [smooch/smooch-android#123]
**Bug report [crash]**

Crash Log:

Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find com.google.gson.annotations.SerializedName.value
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Field.getAnnotation(Field.java:242)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldNames(ReflectiveTypeAdapterFactory.java:74)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.Gson.fromJson(Gson.java:926)
       at com.google.gson.Gson.fromJson(Gson.java:892)
       at com.google.gson.Gson.fromJson(Gson.java:841)
       at com.google.gson.Gson.fromJson(Gson.java:813)
       at io.smooch.core.b.a.c.a(Unknown Source)
       at io.smooch.core.b.c.a(Unknown Source)
       at io.smooch.core.service.SmoochService.a(Unknown Source)
       at io.smooch.core.c.a(Unknown Source)
       at io.smooch.core.c$1.onServiceConnected(Unknown Source)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1265)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1282)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

- SDK version: `5.13.2`

bug details on Fabric:
[http://crashes.to/s/5e36943f91f](url)

**Comment by wmora** [comment]
Fixed in version [5.14.1](https://github.com/smooch/smooch-android/releases/tag/5.14.1)

**Comment by islamassi** [comment]
@wmora 
The issue persists on version `5.14.1`
Fabric:
http://crashes.to/s/9c3700e7680

**Comment by bhavenshahoptimumbrew** [comment]
Yes this happens in most of Samsung's phones. I also got same issue.

I got the solution of it. 

At first all phone's company was ignoring comments ( //  or  /* */ ) in .json File.

But now Samsung developers are not ignoring it. 

So The best Solution is that you have to remove all comment ( // or /* */ ) lines in your .json file
