### ISSUE TITLE
Error on ConversationActivity.show(this);

### ISSUE THREAD

**Issue by djokobozinov** [smooch/smooch-android#22]
Hello, i got this errror
` java.lang.NoSuchFieldError: No static field Smooch_inputText of type I in class Lio/smooch/ui/R$id;
`
when i call ConversationActivity.show(this);
Have anyone expierenced the same?

**Comment by danpetruk** [comment]
Seems like they released buggy version. Switching to 2.2 solves the problem.

   compile 'io.smooch:core:2.2.0'
   compile 'io.smooch:ui:2.2.0'

**Comment by langhoangal** [comment]
The same for me. Thanks for 2.2.0. But is it a tmp solution?

**Comment by djokobozinov** [comment]
@danpetruk it works with 2.2.0, thanks. I hope they will fix the latest version soon.

**Comment by jugarrit** [comment]
Very sorry about this!
We'll work on a fix that should be out today.

**Comment by jugarrit** [comment]
Fixed in 2.3.1

**Comment by sreejithileaf** [comment]
Still getting the same issue
java.lang.NoSuchFieldError: No static field Smooch_inputText of type I in class Lio/smooch/ui/R$id; or its superclasses (declaration of 'io.smooch.ui.R$id' appears in /data/app/chat.smooch.io.smoochchat-1/base.apk)

I'm using eclipse and 'core-3.2.1-classes.jar' and 'ui-3.2.1-classes.jar' in libs folder
